### ISSUE TITLE
ERR-INVALID-USER with api token auth

### ISSUE THREAD

**Issue by rsfez** [etcinit/phabulous#13]
Hi!

I'm facing a `ERR-INVALID-USER: The username you are attempting to authenticate with is not valid.` error soon after the server is launched.

What could be the problem as my conduit conf in the main.yml file looks like this:
```
conduit:
  api: 'https://my-phabricator.com'

  # For token-based auth, use the following key:
  token: 'api-mytoken'

  # For certificate-based auth, use the following keys:
  #user: bruh
  #cert: 'test'
```

Cheers,
