### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Hunsu** [etcinit/phabulous#39]
```
DEBU[1721] epoch=1468229169&storyAuthorPHID=PHID-USER-t6ri6rdnpitrxzehpzg2&storyData%5BobjectPHID%5D=PHID-DREV-osf4mldkw5pusskur6rq&storyData%5BtransactionPHIDs%5D%5BPHID-XACT-DREV-2kbgp7ketmerrf4%5D=PHID-XACT-DREV-2kbgp7ketmerrf4&storyData%5BtransactionPHIDs%5D%5BPHID-XACT-DREV-pemd3jkgtrrbl5z%5D=PHID-XACT-DREV-pemd3jkgtrrbl5z&storyID=11614&storyText=sometext&storyType=PhabricatorApplicationTransactionFeedStory 


2016/07/12 09:22:20 [Recovery] panic recovered:
POST /v1/feed/receive HTTP/1.1
Host: localhost:8085
Accept: */*
Content-Type: application/x-www-form-urlencoded


runtime error: invalid memory address or nil pointer dereference
.gvm/gos/go1.6/src/runtime/panic.go:426 (0x42d2b9)
.gvm/gos/go1.6/src/runtime/panic.go:45 (0x42b969)
.gvm/gos/go1.6/src/runtime/sigpanic_unix.go:24 (0x441c1a)
.gvm/pkgsets/go1.6/global/src/github.com/etcinit/phabulous/app/controllers/feed.go:55 (0x5560ca)
.gvm/pkgsets/go1.6/global/src/github.com/etcinit/phabulous/app/controllers/feed.go:29 (0x5577aa)
.gvm/pkgsets/go1.6/global/src/github.com/gin-gonic/gin/context.go:97 (0x557c7a)
.gvm/pkgsets/go1.6/global/src/github.com/gin-gonic/gin/recovery.go:45 (0x56a511)
.gvm/pkgsets/go1.6/global/src/github.com/gin-gonic/gin/context.go:97 (0x557c7a)
.gvm/pkgsets/go1.6/global/src/github.com/gin-gonic/gin/logger.go:63 (0x5697aa)
.gvm/pkgsets/go1.6/global/src/github.com/gin-gonic/gin/context.go:97 (0x557c7a)
.gvm/pkgsets/go1.6/global/src/github.com/gin-gonic/gin/gin.go:284 (0x55ead2)
.gvm/pkgsets/go1.6/global/src/github.com/gin-gonic/gin/gin.go:265 (0x55e707)
.gvm/gos/go1.6/src/net/http/server.go:2081 (0x698d5e)
.gvm/gos/go1.6/src/net/http/server.go:1472 (0x69560e)
.gvm/gos/go1.6/src/runtime/asm_amd64.s:1998 (0x45de21)
```

**Comment by VeeeneX** [comment]
I fixed it by correcting permissions

**Comment by Saso222** [comment]
Which permissions are those?

**Comment by Roguelazer** [comment]
I'm getting this same panic in a loop. Can you elaborate as to what causes it?

**Comment by turboza** [comment]
We got this kind of error too. It seems we didn't include the `modules` in main.yml. After adding, it worked properly. You may try adapting my test config to use. 

#### phabulous/config/main.yml
```yml
server:
  hostname: ''
  port: 8085
  debug: false
  serious: false
  modules:
    - core
slack:
  token: YOUR_TOKEN_HERE
  username: phabulous
  enable: true
  as-user: true
irc:
  enable: false
  nick: phabulous
  hostname: some.irc.server
  port: 6667
  tls: true
conduit:
  api: http://phabricator.url
  token: YOUR_TOKEN_HERE
channels:
  feed: '#phabricator'
  feedTypes: ['TASK']
core:
  summon:
    expandProjects: true
    includeSelf: true
misc:
  ignore-ca: false
```

in case it still doesn't work, this is my docker-compose config

#### phabulous/docker-compose.yml
```yml
version: '2'
services:
  phabulous:
    image: quay.io/etcinit/phabulous:v3.0.0-beta1
    environment:
      - SLACK_TOKEN=xoxb-000000000000
      - CONDUIT_API=http://phabricator.url
      - CONDUIT_TOKEN=api-xxxxxxxxxxxxxxx
    volumes:
      - 'path_to_phabulous/config:/go/src/github.com/etcinit/phabulous/config'
    ports:
      - '8085:8085'
```
